### ISSUE TITLE
0.17 exact search syntax change

### ISSUE THREAD

**Issue by onexdrk** [RedisLabsModules/RediSearch#67] opened 2017-06-06 16:10 UTC
seems exact search syntax was changed and now need to use ` except "
I think it need to be documented in release notes and may be change parser to work with " for back compatibility

**Comment by dvirsky** [comment] 2017-06-06 17:00
It hasn't changed. Can you demonstrate any regression?

**Comment by onexdrk** [comment] 2017-06-06 22:06
Sure
```
FT.CREATE testExact SCHEMA name TEXT
FT.ADD testExact doc1 1 FIELDS name someName

FT.SEARCH testExact "@name:'someName'"
1) (integer) 1
2) "doc1"
3) 1) "name"
   2) "someName"

FT.SEARCH testExact "@name:\"someName\""
(error) Syntax error at offset 15 near 'someName'

```

In 0.16 same syntax works well

**Comment by dvirsky** [comment] 2017-06-07 05:04
the ' has no meaning, so it's like not writing anything. The reason the quotes did not work is that the parser expects an exact phrase to contain at least two words. That's a minor bug and I'll fix it, but a single word in quotes has no semantic meaning.

**Comment by dvirsky** [comment] 2017-06-07 07:34
Fixed in latest master. Thanks.

**Closed by dvirsky** 2017-06-07 07:34 UTC
