### ISSUE TITLE
presence of indexed document causes BGREWRITEAOF errors

### ISSUE THREAD

**Issue by slowernet** [RedisLabsModules/RediSearch#267] opened 2018-01-19 17:55 UTC
Alternating cli and `redis-server.log` blocks:

```ssh
127.0.0.1:6379[1]> info
# Server
redis_version:4.0.6
...
127.0.0.1:6379[1]> module list
1) 1) "name"
   2) "ft"
   3) "ver"
   4) (integer) 10004
127.0.0.1:6379[1]> keys *
(empty list or set)
127.0.0.1:6379[1]> BGREWRITEAOF
Background append only file rewriting started
```

```
2566:M 19 Jan 12:49:05.989 * Background append only file rewriting started by pid 2871
2566:M 19 Jan 12:49:06.054 * AOF rewrite child asks to stop sending diffs.
2871:C 19 Jan 12:49:06.055 * Parent agreed to stop sending diffs. Finalizing AOF...
2871:C 19 Jan 12:49:06.057 * Concatenating 0.00 MB of AOF diff received from parent.
2871:C 19 Jan 12:49:06.057 * SYNC append only file rewrite performed
2566:M 19 Jan 12:49:06.097 * Background AOF rewrite terminated with success
2566:M 19 Jan 12:49:06.098 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
2566:M 19 Jan 12:49:06.100 * Background AOF rewrite finished successfully
```

```ssh
127.0.0.1:6379[1]> FT.CREATE search_test SCHEMA title TEXT WEIGHT 1
OK
127.0.0.1:6379[1]> BGREWRITEAOF
Background append only file rewriting started
```

```
2566:M 19 Jan 12:49:51.402 * Background append only file rewriting started by pid 2872
2566:M 19 Jan 12:49:51.463 * AOF rewrite child asks to stop sending diffs.
2872:C 19 Jan 12:49:51.463 * Parent agreed to stop sending diffs. Finalizing AOF...
2872:C 19 Jan 12:49:51.465 * Concatenating 0.00 MB of AOF diff received from parent.
2872:C 19 Jan 12:49:51.466 * SYNC append only file rewrite performed
2566:M 19 Jan 12:49:51.524 * Background AOF rewrite terminated with success
2566:M 19 Jan 12:49:51.525 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
2566:M 19 Jan 12:49:51.527 * Background AOF rewrite finished successfully
```

```ssh
127.0.0.1:6379[1]> FT.ADD search_test 'post:1' 1 NOSAVE REPLACE FIELDS title 'Do Androids Dream of Electric Sheep?'
OK
127.0.0.1:6379[1]> FT.SEARCH search_test 'sheep'
1) (integer) 1
2) "post:1"
3) (empty list or set)
127.0.0.1:6379[1]> BGREWRITEAOF
Background append only file rewriting started
```

```
2566:M 19 Jan 12:50:39.054 * Background append only file rewriting started by pid 2874
2874:C 19 Jan 12:50:39.056 # <ft> Failed to emit AOF
2874:C 19 Jan 12:50:39.056 # <ft> Failed to emit AOF
2874:C 19 Jan 12:50:39.059 # <ft> Failed to emit AOF
2874:C 19 Jan 12:50:39.059 # <ft> Failed to emit AOF
2874:C 19 Jan 12:50:39.061 # <ft> Failed to emit AOF
2874:C 19 Jan 12:50:39.061 # <ft> Failed to emit AOF
2874:C 19 Jan 12:50:39.061 # <ft> Failed to emit AOF
2566:M 19 Jan 12:50:39.130 * AOF rewrite child asks to stop sending diffs.
2874:C 19 Jan 12:50:39.130 * Parent agreed to stop sending diffs. Finalizing AOF...
2874:C 19 Jan 12:50:39.133 * Concatenating 0.00 MB of AOF diff received from parent.
2874:C 19 Jan 12:50:39.133 * SYNC append only file rewrite performed
2566:M 19 Jan 12:50:39.162 * Background AOF rewrite terminated with success
2566:M 19 Jan 12:50:39.162 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
2566:M 19 Jan 12:50:39.165 * Background AOF rewrite finished successfully
```

```ssh
127.0.0.1:6379[1]> FT.DROP search_test
OK
127.0.0.1:6379[1]> BGREWRITEAOF
Background append only file rewriting started
```

```
2566:M 19 Jan 12:52:37.132 * Background append only file rewriting started by pid 2878
2566:M 19 Jan 12:52:37.192 * AOF rewrite child asks to stop sending diffs.
2878:C 19 Jan 12:52:37.192 * Parent agreed to stop sending diffs. Finalizing AOF...
2878:C 19 Jan 12:52:37.194 * Concatenating 0.00 MB of AOF diff received from parent.
2878:C 19 Jan 12:52:37.195 * SYNC append only file rewrite performed
2566:M 19 Jan 12:52:37.277 * Background AOF rewrite terminated with success
2566:M 19 Jan 12:52:37.277 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
2566:M 19 Jan 12:52:37.279 * Background AOF rewrite finished successfully
```

---

For completeness, I also experienced a different (fatal) error when trying to `BGREWRITEAOF` with an older version of RediSearch:

```
1921:C 19 Jan 12:17:09.370 # Fatal: AOF method for module data type 'trietype0' tried to call RedisModule_EmitAOF() with wrong format specifiers 'sbdbb'
1921:C 19 Jan 12:17:09.372 # Write error writing append only file on disk: Invalid argument
1675:M 19 Jan 12:17:09.415 # Background AOF rewrite terminated with error
```

Thanks for your time.

**Comment by dvirsky** [comment] 2018-01-19 18:41
@mnunberg please recreate and try to make sense of it. Thanks.

**Comment by mnunberg** [comment] 2018-01-19 19:48
@slowernet is there anything unique about your environment that we should know? The only codepath that leads to the 'Failed to emit EOF' is when the key itself wouldn't be present (i.e. `DUMP` is called unsuccessfully.

I think the first step to debugging this is figuring out what the culprit key (in 'DUMP') was that failed

**Comment by mnunberg** [comment] 2018-01-19 20:04
So the code should create 8 redis keys, and it shows it's failing 7 of them; so the error might be in the first key which would cause it to end up in an invalid state. Can you post the (failed) AOF file? it should have at least one entry.

Needless to say, I can't reproduce it, and valgrind isn't cranky either.

Is this 32 bit perhaps?

**Comment by slowernet** [comment] 2018-01-19 21:24
In the initial bug I tried to isolate by using a clean DB, but I do have other stuff in this instance that prevents me from posting the AOF. Let me try with a totally clean instance next.

It's a 64-bit build:

```ssh
127.0.0.1:6379[1]> info
# Server
redis_version:4.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4a12ccd68263c36b
redis_mode:standalone
os:Darwin 16.7.0 x86_64
arch_bits:64
multiplexing_api:kqueue
atomicvar_api:atomic-builtin
gcc_version:4.2.1
process_id:2566
run_id:74d285fe045f9d3036fc0048eba2040ca4a07cfd
tcp_port:6379
uptime_in_seconds:14332
uptime_in_days:0
hz:10
lru_clock:6447479
executable: ...
config_file:/usr/local/etc/redis.conf
```

**Comment by mnunberg** [comment] 2018-01-19 21:41
Another thing you can do is `DUMP <key>` where `<key>` is each key from `KEYS *` (you should only have 8). This will show the error more closely.

**Comment by dvirsky** [comment] 2018-01-19 22:02
@slowernet any chance there's another module running on the same instance?

**Comment by slowernet** [comment] 2018-01-19 22:10
@mnunberg:
```
127.0.0.1:6379[1]> keys *
(empty list or set)
127.0.0.1:6379[1]> FT.CREATE search_test SCHEMA title TEXT WEIGHT 1
OK
127.0.0.1:6379[1]> FT.ADD search_test 'post:1' 1 NOSAVE REPLACE FIELDS title 'Do Androids Dream of Electric Sheep?'
OK
127.0.0.1:6379[1]> keys *
1) "idx:search_test"
2) "ft:search_test/+electr"
3) "ft:search_test/+android"
4) "ft:search_test/dream"
5) "ft:search_test/androids"
6) "ft:search_test/electric"
7) "ft:search_test/sheep"
8) "ft:search_test/do"
127.0.0.1:6379[1]> BGREWRITEAOF
Background append only file rewriting started
127.0.0.1:6379[1]> DUMP idx:search_test
"\a\x81~\xdf\xe2\x9d\xd7\xb1\xd0\n\x05\x0csearch_test\x00\x02@S\x02\x01\x05\x06title\x00\x02\x00\x02\x00\x02\x81\xff\xff\xff\xff\xff\xff\xff\xff\x02\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x02\x01\x02\a\x02\a\x02*\x02\x00\x02\x00\x02\x00\x02\a\x02\a\x02+\x02\x02\x02\x01\x05\x06post:1\x02\x00\x02\x01\x02\a\x03\x00\x00\x80?\x02\a\x05\x03do\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x05\x06dream\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x05\b+electr\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x05\t+android\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x05\telectric\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x05\tandroids\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x05\x06sheep\x00\x04\x00\x00\x00\x00\x00\x00\xf0?\x00\b\x00\x11\n\xc4;e>E\xfe"
127.0.0.1:6379[1]> DUMP ft:search_test/+electr
"\a\x81~\xdf\xe2\x9e\xf8\x9d\xc4\x01\x02@S\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x05\x06\x00\x01\x01\x01\x01\x04\x00\b\x00\xa8A\xca\xa5\x9ca\xa3\xcf"
127.0.0.1:6379[1]> DUMP ft:search_test/+android
"\a\x81~\xdf\xe2\x9e\xf8\x9d\xc4\x01\x02@S\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x05\x06\x00\x01\x01\x01\x01\x02\x00\b\x00\x01\xbeee z\x0f\x98"
127.0.0.1:6379[1]> DUMP ft:search_test/dream
"\a\x81~\xdf\xe2\x9e\xf8\x9d\xc4\x01\x02@S\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x05\x06\x00\x01\x01\x01\x01\x03\x00\b\x00\a\xdd\x1c\xe9C\x12\xee\x14"
127.0.0.1:6379[1]> DUMP ft:search_test/androids
"\a\x81~\xdf\xe2\x9e\xf8\x9d\xc4\x01\x02@S\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x05\x06\x00\x01\x01\x01\x01\x02\x00\b\x00\x01\xbeee z\x0f\x98"
127.0.0.1:6379[1]> DUMP ft:search_test/electric
"\a\x81~\xdf\xe2\x9e\xf8\x9d\xc4\x01\x02@S\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x05\x06\x00\x01\x01\x01\x01\x04\x00\b\x00\xa8A\xca\xa5\x9ca\xa3\xcf"
127.0.0.1:6379[1]> DUMP ft:search_test/sheep
"\a\x81~\xdf\xe2\x9e\xf8\x9d\xc4\x01\x02@S\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x05\x06\x00\x01\x01\x01\x01\x05\x00\b\x00\xae\"\xb3)\xff\tBC"
127.0.0.1:6379[1]> DUMP ft:search_test/do
"\a\x81~\xdf\xe2\x9e\xf8\x9d\xc4\x01\x02@S\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x02\x01\x05\x06\x00\x01\x01\x01\x01\x01\x00\b\x00`\x88y\xa9\xd7\xe4u&"
```

@dvirsky No other modules. Full output:
```
127.0.0.1:6379[1]> module list
1) 1) "name"
   2) "ft"
   3) "ver"
   4) (integer) 10004
```

**Comment by dvirsky** [comment] 2018-01-19 22:35
That is starting to feel weird - I can't recreate it with these exact same steps. What version of redisearch is this?

**Comment by dvirsky** [comment] 2018-01-19 22:42
Oh, I see that it's 1.0.4 which is the latest. I can't recreate it on either mac or linux. @mnunberg thoughts?

**Comment by dvirsky** [comment] 2018-01-19 23:03
OHHHHH I know what it is. You're creating the index on redis db 1 and the code in question runs the DUMP command on db 0. It's a simple fix, let me try something...

**Comment by dvirsky** [comment] 2018-01-19 23:18
Ok, this can't be fixed. This is actually due to a limitation/bug of redis itself. We don't know on which DB the key actually resides, and the io context doesn't tell us that. So we cannot actually open its content and dump that to AOF. 

For now @slowernet just don't use redisearch (or any other redis module) in a db number other than 0. 

@mnunberg we need to discuss the two alternatives - either push for a fix in redis itself, or bypass the whole dump/restore thing and do something else.

**Comment by slowernet** [comment] 2018-01-20 06:17
Noted. 

Thanks for digging in and for filing the linked issue @dvirsky, @mnunberg.

**Comment by dvirsky** [comment] 2018-01-20 10:02
For now we will verify that when creating an index, you are doing it on db 0, and fail if you don't. It's better than chasing issues like this. Thanks for reporting.

**Comment by dvirsky** [comment] 2018-01-21 16:07
Closing this as it's not fixable and we'll bypass the issue as described on #271

**Closed by dvirsky** 2018-01-21 16:07 UTC
