### ISSUE TITLE
FT.AGGREGATE fails when field filter is 'A'

### ISSUE THREAD

**Issue by kavinduchamiran** [RedisLabsModules/RediSearch#509] opened 2018-10-08 05:36 UTC
I'm facing a bug in FT.AGGREGATE command when I try to filter the documents using @field:value syntax and my filter value is character 'A'. See the screenshot below.

![kavindu kavindu-hp-probook-450-g4 _007](https://user-images.githubusercontent.com/25504785/46593313-8e189800-cae8-11e8-85ef-aefe9cfb4240.png)

You can clearly see that there is a document titled 'A' but when I try to search it, it gives an "**Internal error processing QueryParseCtx**" error. The command works for other 2 documents titled 'B' and 'C'. The problem is only for character 'A'.

I have attached the index information in the screenshot below.

![kavindu kavindu-hp-probook-450-g4 _009](https://user-images.githubusercontent.com/25504785/46593312-8d800180-cae8-11e8-92cc-3f5ab3faf8d6.png)

Any fix for this bug?

**Comment by itamarhaber** [comment] 2018-10-08 07:02
Hello @kavinduchamiran 

I believe the issue is caused because 'A' is one of the default [stop-words](https://oss.redislabs.com/redisearch/Stopwords/). You can recreate the index and define your own stop-words, if needed, without 'A'.

That said, the error you've experienced is unpleasant and uninformative, so let's keep this issue open as a reminder to fix it.

**Comment by kavinduchamiran** [comment] 2018-10-08 07:04
> Hello @kavinduchamiran
> 
> I believe the issue is caused because 'A' is one of the default [stop-words](https://oss.redislabs.com/redisearch/Stopwords/). You can recreate the index and define your own stop-words, if needed, without 'A'.
> 
> That said, the error you've experienced is unpleasant and uninformative, so let's keep this issue open as a reminder to fix it.

Thanks for the information. I will try defining the stop words.

**Comment by MeirShpilraien** [comment] 2018-10-08 08:02
@kavinduchamiran what is the redisearch version you are using?

**Comment by kavinduchamiran** [comment] 2018-10-08 08:03
Latest version. 1.4 as I remember.

**Comment by MeirShpilraien** [comment] 2018-10-08 08:04
Can you pleas send the commands you performed to reproduce the issue?

**Comment by MeirShpilraien** [comment] 2018-10-08 08:08
Ok I reproduce the issue on 1.4, the good news is that on master you get a correct error message:
```
127.0.0.1:6379> FT.AGGREGATE imdb_db_idx "@primaryName:A"
(error) Query matches no results
```
So it will be fixed on the next release (1.4.1)

@kavinduchamiran Thanks for reporting.

**Comment by kavinduchamiran** [comment] 2018-10-08 08:14
> Can you pleas send the commands you performed to reproduce the issue?
> How you inserted the data?

I'm using the redisearch python client.

client = Client('index_name')

client.create_index([
    TextField('title', sortable=True),
    TextField('body', sortable=True)
])

client.add_document(
    'doc1',
    **{
        'body' : 'text1',
        'title': 'A'
    }
)

About the inaccurate error message, the screenshot was from an older version. And yes, in the latest version, it produces a more informative error message.

**Comment by kavinduchamiran** [comment] 2018-10-10 05:59
@itamarhaber @MeirShpilraien @dvirsky I have another question but I do not want to open another issue because I'm not sure whether this is an issue of redisearch or not.

Is there anyway to execute a case sensitive search? Currently both 'A' and 'a' return the same results.

**Comment by MeirShpilraien** [comment] 2018-10-10 13:46
Currently its not possible, we will add it in future releases.

**Closed** 2018-11-18 11:51 UTC
