### ISSUE TITLE
FT.search with SORTYBY crashes redis server 

### ISSUE THREAD

**Issue by vlradstake** [RedisLabsModules/RediSearch#603] opened 2019-02-14 09:46 UTC
The following query crashes the redis server:
`FT.SEARCH products "@category_ids:{204} @stock_status:[1 1]" LANGUAGE dutch WITHSCORES LIMIT 0 33 SORTBY name ASC`

If we execute the query without `SORTBY name` or with `SORTBY created_at` redis server shows the result as expected. 

Bug report redis server:

`
=== REDIS BUG REPORT START: Cut & paste starting from here ===
2004:M 13 Feb 12:54:06.870 # Redis 4.0.11 crashed by signal: 11
2004:M 13 Feb 12:54:06.870 # Crashed running the instruction at: 0x7f8f20a0db8f
2004:M 13 Feb 12:54:06.870 # Accessing address: (nil)
2004:M 13 Feb 12:54:06.870 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/etc/redis/modules/redisearch-1.4.2.so(DocTable_Exists+0x3f)[0x7f8f20a0db8f]

Backtrace:
/usr/bin/redis-server 0.0.0.0:6090(logStackTrace+0x5a)[0x55fb29d6065a]
/usr/bin/redis-server 0.0.0.0:6090(sigsegvHandler+0xb1)[0x55fb29d60e11]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f8f23068890]
/etc/redis/modules/redisearch-1.4.2.so(DocTable_Exists+0x3f)[0x7f8f20a0db8f]
/etc/redis/modules/redisearch-1.4.2.so(IndexBlock_Repair+0x119)[0x7f8f20a1c8d9]
/etc/redis/modules/redisearch-1.4.2.so(InvertedIndex_Repair+0x6c)[0x7f8f20a1cb0c]
/etc/redis/modules/redisearch-1.4.2.so(gc_RandomTerm+0x277)[0x7f8f20a0c9c7]
/etc/redis/modules/redisearch-1.4.2.so(GC_PeriodicCallback+0xd3)[0x7f8f20a0d3c3]
/etc/redis/modules/redisearch-1.4.2.so(+0x4d507)[0x7f8f20a15507]
/etc/redis/modules/redisearch-1.4.2.so(+0xaf530)[0x7f8f20a77530]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f8f2305d6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f8f22d8688f]

------ INFO OUTPUT ------
# Server
redis_version:4.0.11
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4bc3aa215ca9cf78
redis_mode:standalone
os:Linux 4.15.0-45-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.3.0
process_id:2004
run_id:587c18696b10eeff2d637ac2b8078dca84e35292
tcp_port:6090
uptime_in_seconds:11
uptime_in_days:0
hz:10
lru_clock:6558574
executable:/usr/bin/redis-server
config_file:/etc/redis/redis-hi-instant.dewitschijndel.nl.conf

# Clients
connected_clients:2
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:293495160
used_memory_human:279.90M
used_memory_rss:330711040
used_memory_rss_human:315.39M
used_memory_peak:293514224
used_memory_peak_human:279.92M
used_memory_peak_perc:99.99%
used_memory_overhead:5162596
used_memory_startup:786832
used_memory_dataset:288332564
used_memory_dataset_perc:98.51%
total_system_memory:4136538112
total_system_memory_human:3.85G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.13
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1550062435
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:3
total_commands_processed:5
instantaneous_ops_per_sec:1
total_net_input_bytes:84
total_net_output_bytes:126
instantaneous_input_kbps:0.02
instantaneous_output_kbps:0.01
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:816
keyspace_misses:11
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:1c7367fc0cd4e2d2e30388d021b7238f93b27778
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.27
used_cpu_user:3.33
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_ping:calls=4,usec=5,usec_per_call=1.25
cmdstat_info:calls=1,usec=93,usec_per_call=93.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=82336,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=100 addr=83.217.93.49:40900 fd=7 name= age=2 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=137 addr=83.217.93.49:40996 fd=8 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping

------ REGISTERS ------
2004:M 13 Feb 12:54:06.871 # 
RAX:0000000000000000 RBX:0000000000000017
RCX:00000000000f4240 RDX:017600fffefefefe
RDI:00007f8f12108580 RSI:00000000000d91d7
RBP:00007f8f0b463af0 RSP:00007f8f0bffebc8
R8 :00007f8f0346e896 R9 :0000000000000000
R10:0200000000000000 R11:0000000000000001
R12:00000000000d91d7 R13:00007f8f035b5700
R14:00007f8f0bffed30 R15:0000000000000001
RIP:00007f8f20a0db8f EFL:0000000000010202
CSGSFS:002b000000000033
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd7) -> 0000000000000000
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd6) -> 000000000000017f
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd5) -> 00007f8f0346e880
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd4) -> 00007f8f0346e880
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd3) -> 00007f8f0bffec30
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd2) -> 0000000000000017
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd1) -> 000055fb2cbfb610
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebd0) -> 0000000000123707
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebcf) -> 00007f8f0bffec20
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebce) -> 00007f8f20a1bad0
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebcd) -> 00007f8f0bffec10
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebcc) -> 00007f8f12108580
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebcb) -> 00007f8f20a1a750
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebca) -> 0000000000000000
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebc9) -> 0000000000000000
2004:M 13 Feb 12:54:06.871 # (00007f8f0bffebc8) -> 00007f8f20a1c8d9

------ FAST MEMORY TEST ------
2004:M 13 Feb 12:54:06.871 # Bio thread for job type #0 terminated
2004:M 13 Feb 12:54:06.872 # Bio thread for job type #1 terminated
2004:M 13 Feb 12:54:06.872 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55fb2a03f000 (94208 bytes)
*** Preparing to test memory region 55fb2b27b000 (28164096 bytes)
*** Preparing to test memory region 7f8efc000000 (135168 bytes)
*** Preparing to test memory region 7f8f02e00000 (142606336 bytes)
*** Preparing to test memory region 7f8f0b800000 (167772160 bytes)
*** Preparing to test memory region 7f8f159b3000 (8388608 bytes)
*** Preparing to test memory region 7f8f161b4000 (8388608 bytes)
*** Preparing to test memory region 7f8f169b5000 (8388608 bytes)
*** Preparing to test memory region 7f8f171b6000 (8388608 bytes)
*** Preparing to test memory region 7f8f179b7000 (8388608 bytes)
*** Preparing to test memory region 7f8f181b8000 (8388608 bytes)
*** Preparing to test memory region 7f8f189b9000 (8388608 bytes)
*** Preparing to test memory region 7f8f191ba000 (8388608 bytes)
*** Preparing to test memory region 7f8f199bb000 (8388608 bytes)
*** Preparing to test memory region 7f8f1a1bc000 (8388608 bytes)
*** Preparing to test memory region 7f8f1a9bd000 (8388608 bytes)
*** Preparing to test memory region 7f8f1b1be000 (8388608 bytes)
*** Preparing to test memory region 7f8f1b9bf000 (8388608 bytes)
*** Preparing to test memory region 7f8f1c1c0000 (8388608 bytes)
*** Preparing to test memory region 7f8f1c9c1000 (8388608 bytes)
*** Preparing to test memory region 7f8f1d1c2000 (8388608 bytes)
*** Preparing to test memory region 7f8f1d9c3000 (8388608 bytes)
*** Preparing to test memory region 7f8f1e1c4000 (8388608 bytes)
*** Preparing to test memory region 7f8f1e9c5000 (8388608 bytes)
*** Preparing to test memory region 7f8f1f1c6000 (8388608 bytes)
*** Preparing to test memory region 7f8f1f9c7000 (8388608 bytes)
*** Preparing to test memory region 7f8f201c8000 (8388608 bytes)
*** Preparing to test memory region 7f8f20dfa000 (12288 bytes)
*** Preparing to test memory region 7f8f20dfe000 (8388608 bytes)
*** Preparing to test memory region 7f8f215ff000 (8388608 bytes)
*** Preparing to test memory region 7f8f21e00000 (10485760 bytes)
*** Preparing to test memory region 7f8f22a00000 (2097152 bytes)
*** Preparing to test memory region 7f8f23052000 (16384 bytes)
*** Preparing to test memory region 7f8f23271000 (16384 bytes)
*** Preparing to test memory region 7f8f23a33000 (16384 bytes)
*** Preparing to test memory region 7f8f23a40000 (4096 bytes)
`

gdb
https://drive.google.com/file/d/1BwsIjoZ5lsHQFIJ-vR0GIMhp7koCgi2C/view?usp=sharing

**Comment by mnunberg** [comment] 2019-02-14 11:58
This looks like a duplicate of #595

**Comment by mnunberg** [comment] 2019-02-17 11:45
Closing this, as #595 is fixed

**Closed by mnunberg** 2019-02-17 11:45 UTC
