### ISSUE TITLE
Order of the query conditions yields different (incorrect) results

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#247] opened 2017-12-18 15:23 UTC
Take this data:
```
FT.CREATE ted SCHEMA colours TAG price numeric
FT.ADD ted apple 1 FIELDS colours "yellow,green,red" price 0.99
FT.ADD ted pear 1 FIELDS colours "yellow,green,brown" price 1.99
FT.ADD ted banana 1 FIELDS colours "yellow" price 0.25
FT.ADD ted lemon 1 FIELDS colours "yellow" price 0.50
FT.ADD ted lime 1 FIELDS colours "green" price 0.50
```
Then query it as so:
```
> FT.SEARCH ted "-(@colours:{ red }) @price:[0.49 +inf]" NOCONTENT
1) (integer) 4
2) "lime"
3) "lemon"
4) "banana"
5) "pear"
```
(note the incorrect inclusion of `banana` which has a `price` of 0.25)

However, if you query it with the two condition positions reversed, you get the correct results:
```
> FT.SEARCH ted "@price:[0.49 +inf] -(@colours:{ red })" NOCONTENT
1) (integer) 3
2) "lime"
3) "lemon"
4) "pear"
```

(`NOCONTENT` is included just for concise results, same issue with or without it)

**Comment by salt4pommes** [comment] 2017-12-19 13:24
Also interesting:
FT.SEARCH ted "@price:[0.49 +inf]" NOCONTENT

Result:
1) (integer) 4
2) "lime"
3) "lemon"
4) "pear"
5) "apple"

Numeric filter seems to have a bug

**Comment by salt4pommes** [comment] 2017-12-19 13:26
When using FT.SEARCH ted "@price:[0.49 1.0]" NOCONTENT

Result:
1) (integer) 3
2) "lime"
3) "lemon"
4) "apple"

+inf seems to make problems here

**Comment by dvirsky** [comment] 2017-12-19 13:31
it's not the inf itself, it's probably a bug in the union algorithm. I'll investigate.

**Comment by dvirsky** [comment] 2017-12-19 14:51
@salt4pommes I don't see an issue with what you've brought up. 
```
127.0.0.1:6379> FT.SEARCH ted "@price:[0.49 +inf]" RETURN 1 price
1) (integer) 4
2) "lime"
3) 1) "price"
   2) "0.50"
4) "lemon"
5) 1) "price"
   2) "0.50"
6) "pear"
7) 1) "price"
   2) "1.99"
8) "apple"
9) 1) "price"
   2) "0.99"
127.0.0.1:6379> FT.SEARCH ted "@price:[0.49 1]" RETURN 1 price
1) (integer) 3
2) "lime"
3) 1) "price"
   2) "0.50"
4) "lemon"
5) 1) "price"
   2) "0.50"
6) "apple"
7) 1) "price"
   2) "0.99"
```

The issue is with the negative filter

**Comment by dvirsky** [comment] 2017-12-19 15:07
@stockholmux the issue is more trivial, it's a parser ambiguity. basically had you tried EXPLAIN you would have seen:
```
NOT{
  INTERSECT {
    TAG:@colours {
      red
    }
    NUMERIC {0.490000 <= @price <= inf}
  }
}
```
basically "anything that's not an apple". That's because the dash is applied to the entire query. Putting it in the parentheses is the acutal query you mean and yields the correct results.

```
127.0.0.1:6379> FT.EXPLAIN ted "(-@colours:{ red }) @price:[0.49 +inf]" RETURN 1 price
INTERSECT {
  NOT{
    TAG:@colours {
      red
    }
  }
  NUMERIC {0.490000 <= @price <= inf}
}

127.0.0.1:6379> FT.SEARCH ted "(-@colours:{ red }) @price:[0.49 +inf]" RETURN 1 price
1) (integer) 3
2) "lime"
3) 1) "price"
   2) "0.50"
4) "lemon"
5) 1) "price"
   2) "0.50"
6) "pear"
7) 1) "price"
   2) "1.99"
```

**Comment by dvirsky** [comment] 2017-12-19 15:11
I'm closing this. I'm not sure it's the wrong behavior in the parser to be hones. "solving" it will require a broader effort of a more formal definition of the language and the precedence rules.

**Closed by dvirsky** 2017-12-19 15:11 UTC

**Comment by salt4pommes** [comment] 2017-12-19 15:52
You're right, it was my fault :)
Sorry, I've testet it too quickly and doesn't realized that the missing value was gone because of my faulty query :)
